title: "Predicting Drug Resistance in Malaria Using Language Learning Models"
description: "Authors - Aditya Arun, Annie Pham, Aryan Shah, and Jared Simpauco"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
